token:
  expiration_time: 864000000 
  secret: '{cipher}AYBmPVlM22YhKzHaZcXPB8o9PFZSAbjp/H4PFaD42sJKszZaf1kMSD/Y9FhaHxQVOgDKGf/RY9hqTkMNNi77ONM7C+IKCkTf6dCUo+UkzZiLn00nMEjOjMZ3T9pg5Z+iFO+iPOYwHKpH4L1DcwkSKUq1cYL5YACF2ydqB82RjSQyOdm6vJaiO8ScBrFp6Cv06ZWTVD60nhNwgySCcQ4CeitIOVM5+187DecgFknQUdVo9x2FSyMd1/EyAU1A1kszNqMg+hzlYQ9y6OBPLwTnthzux1WxdIlBZFNI0y4U7jCvZaEpajBRyPHN+iP7IHXyTi/A5kXSYOhAUxEmVwOvsHDHJnOZV0wg++juQjGtU1YG1NakNNHM5sFLdAsnzPDi46Ga9DjPAyKx9Sd4b7qe1UfX7oSMsT3W1Svg3Bc069dLecq/h3g3x3iulbDEruONSa0V3nrLC7/HsPik/bJTvp+HQJ9ruZDGEXTIFLLMsH4rR+F/ZOd5fbmut/ccnHMKBwTw3f/noeKEHng2zW5t5m7hzD7WLLs0DpZsOBWdHrys/g=='

gateway:
  ip: 172.18.0.1