token:
  expiration_time: 864000000 
  secret: '{cipher}AYAHxJM+ldLm6hWOpnFPrHEbZdYR7j+sTGnO+XPU3SzjR7yXiaY6Ewr3nAXPvcnkR8HlO7+YtKS0N+fDTnLlLYgU5FF1VaZ81gp7dvoD+uu/liGv3z6G4GyXREgpNXkDPYNCSEtsXCDuhfx8wq84cpxQx46T7ebDJo5aldjJYl3uznZ/TQ+PaETqyrn8+sGYW8sBbLiqVPXbngs7QFmJpiVoliip2IkRTy6YsIyrnuF6HuM51aPIIHg47mgApuWKRuFknPXi45GoKXltS/YjVKSVJErtkTiTRVgmDcZzln0AN7zYDCfygxsgBRFde1mEipROAfsB4y6WJXprqENuotiA5zoNFUkVtMSlGiHBAhbGOGh3W4wI8VoTB6Fzy/nuw9HaScGX8xEdbePm7edRNNyja2D38sZHlyibFeZzKnrolpaUDKTdxShMhz52sPKRmvp7GHvU41hN+Y+/XEoIbSlHf12jKJrc0cOAd90swl6syLrqrUl7aeYoCA+KJmms5V3iXeEjLrczLtAPioLfWax0N/5dTR2lpKImBRwcU4CDKQMit1x4kZGT+3GDa/7ho8OO3Yi6f1bPP+FvOYxLDWj1o7SW29nGsReG9tm5ke22Qw=='

gateway:
  ip: 172.18.0.1