spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}09ab6edb2bfe6f2649e619ef7b914fd6862b44d5619bcac1fa2be6b5ac8a67d9AYBmPVlM22YhKzHaZcXPB8o9PFZSAbjp/H4PFaD42sJKszZaf1kMSD/Y9FhaHxQVOgDKGf/RY9hqTkMNNi77ONM7C+IKCkTf6dCUo+UkzZiLn00nMEjOjMZ3T9pg5Z+iFO+iPOYwHKpH4L1DcwkSKUq1cYL5YACF2ydqB82RjSQyOdm6vJaiO8ScBrFp6Cv06ZWTVD60nhNwgySCcQ4CeitIOVM5+187DecgFknQUdVo9x2FSyMd1/EyAU1A1kszNqMg+hzlYQ9y6OBPLwTnthzux1WxdIlBZFNI0y4U7jCvZaEpajBRyPHN+iP7IHXyTi/A5kXSYOhAUxEmVwOvsHDHJnOZV0wg++juQjGtU1YG1NakNNHM5sFLdAsnzPDi46Ga9DjPAyKx9Sd4b7qe1UfX7oSMsT3W1Svg3Bc069dLecq/h3g3x3iulbDEruONSa0V3nrLC7/HsPik/bJTvp+HQJ9ruZDGEXTIFLLMsH4rR+F/ZOd5fbmut/ccnHMKBwTw3f/noeKEHng2zW5t5m7hzD7WLLs0DpZsOBWdHrys/g=='

# order-service:
#   # url: http://127.0.0.1:8000/order-service/%s/orders
#   url: http://order-service/order-service/%s/orders
#   exception:
#     order-is-empty: User's orders is empty.